### ISSUE TITLE
Display letter summary in search results

### ISSUE THREAD

**Issue by svandaalen** [knaw-huc/textannoviz#101]
Request from Nina:

> Ik zou daaronder ook graag hebben dat de summary in Engels zichtbaar is, dan kunnen mensen eventueel meteen zien of deze brief nuttig is voor hen (dat stond ook in onze wensenlijst, maar dat hebben we bij vorig overleg niet meer besproken, zie https://edition-humboldt.de/briefe/index.xql?l=en waar ze begin van de brief geven, maar lijkt me ideaal voor de samenvatting).

**Comment by svandaalen** [comment]
This also requires some work on the side of Broccoli. In any way, shape, or form the summaries have to be added to the Elastic index so that TAV can display the summaries in the search hits. Are we going to add them as type `text`? Where does Broccoli get the summaries from? The summaries sit in `body.metadata.summary` of a `tf:File` annotation.

**Comment by hayco** [comment]
Next step forward is to add `body.metadata.summary` to the index. This will cause ES to index the `summary` field and makes it 'findable'. It will also add `summary` to search results passed by 🥦.

**Comment by hayco** [comment]
The Suriano index used in [TAV](https://suriano-tav.tt.di.huc.knaw.nl/) now contains a `summary` field.

**Comment by hayco** [comment]
Highlighting search terms in index fields requires some changes in 🥦 -> knaw-huc/broccoli#49

**Comment by svandaalen** [comment]
This functionality has been added in TAV in https://github.com/knaw-huc/textannoviz/commit/f6b645310065d7cbca346542f15c744eaa016fab.
