### ISSUE TITLE
Multi-select facets

### ISSUE THREAD

**Issue by svandaalen** [knaw-huc/textannoviz#102]
Republic context: allow for the user to select 'maandag' or 'tuesday', etc. When the user now selects 'maandag', all other facet items disappear because the facet internally has an AND relation between the items (and 'maandag' is mutually exclusive with all the other "day of the week" facet values).

See: https://vinted.engineering/2023/03/21/faceted-search-using-elasticsearch/ for information on how Vinted solved this issue.

**Comment by hayco** [comment]
This needs to be solved in 🥦 by hitting Elastic multiple times:

- first do the entire query, fetching hits and aggregations
- then, for each 'term' (facet): redo the query without current term fetching only the aggregations for current term
- finally, merge the above results

**Comment by hayco** [comment]
[Broccoli PR #44](https://github.com/knaw-huc/broccoli/pull/44#issuecomment-2069208021) is klaar voor testen met TAV.
Draait al op TT portainer, dus Republic testen kan.
