### ISSUE TITLE
Browse through search results on detail page with prev/next buttons

### ISSUE THREAD

**Issue by BasLee** [knaw-huc/textannoviz#118]
- Allow disabling the buttons using a configuration property
- When the 'es-search-results-page' has been finished, request new ES-page
- Where to put buttons? During development in the footer, next to search.

Related to: 
- https://github.com/knaw-huc/textannoviz/issues/106
- https://github.com/knaw-huc/textannoviz/issues/87
- https://github.com/knaw-huc/textannoviz/issues/51
- https://github.com/knaw-huc/textannoviz/issues/59

**Comment by kintopp** [comment]
Also related to https://github.com/knaw-huc/textannoviz/issues/59 This sounds like something worth discussing across all TAV implementations?

**Comment by BasLee** [comment]
PR https://github.com/knaw-huc/textannoviz/pull/133

**Comment by svandaalen** [comment]
This has been implemented.
