### ISSUE TITLE
Display annotation information of entities in logical text view

### ISSUE THREAD

**Issue by BasLee** [knaw-huc/textannoviz#119]
- Use annotation anchors to select entities in text view
- Implement design of @Doppen 
- Look at line based implementation of annotation visualization by @svandaalen for some inspiration

How to find coordinates of annotation in logical text?
- find(a => a.type== "LogicalText" && a.selector)
- start and end marks paragraph (absolute), but use ID to find anno's back in views (relative start and end)
- beginCharOffset and endCharOffset mark characters in paragraph, missing now?

Questions:
- How to render metadata? In popup ([popover](https://react-spectrum.adobe.com/react-aria/Popover.html)), in modal?
- How to handle annotations that span multiple paragraphs?
- How to handle nested annotations?
- Should we handle overlapping (not nested) annotations?
- How to handle multiple sources (brocolli > annorepo; team SD-browser? ...?)
 
Related to:
- https://github.com/knaw-huc/textannoviz/issues/97
- https://github.com/knaw-huc/textannoviz/issues/80

**Comment by svandaalen** [comment]
Broccoli example:
https://broccoli.tt.di.huc.knaw.nl/projects/republic/urn:republic:session-3192-num-6-attendance_list?overlapTypes=AttendanceList,RepublicParagraph,Attendant,Resolution,Reviewed,Session,Scan&includeResults=anno,iiif,text&views=self&relativeTo=Origin

Broccoli example 2:
https://broccoli.tt.di.huc.knaw.nl/projects/republic/urn:republic:session-3816-num-95-resolution-3?overlapTypes=AttendanceList,RepublicParagraph,Attendant,Resolution,Reviewed,Session,Scan&includeResults=anno,iiif,text&views=self&relativeTo=Origin

Republic resolution with Entity annotations:
`urn:republic:session-3801-num-213-resolution-6`

**Comment by BasLee** [comment]
(Examples taken from [session-3770-num-202-resolution-4](http://localhost:5173/detail/urn:republic:session-3770-num-202-resolution-4))

Bugs / imperfections:
- When deeply nested, icons do not align with underline/overline:
![image](https://github.com/knaw-huc/textannoviz/assets/3323006/ac320fa2-fa84-4738-a79b-6e94e9f1d383)
- Icon adds inline whitespace:
![image](https://github.com/knaw-huc/textannoviz/assets/3323006/f119f0df-8d3d-415b-a7c0-722a728cc574)
- The icon is showing, but the location is not underlined in this deeply nested annotation:
![image](https://github.com/knaw-huc/textannoviz/assets/3323006/8752f258-9604-4510-b8b5-288f71b73db2)

Additional functionality:
- How to visualize annotations that span a whole line or even multiple lines? For example, when marking a resolution:
![image](https://github.com/knaw-huc/textannoviz/assets/3323006/838a7ef6-0a5b-4ab4-8f3b-770c52237653)
- The new under-overline styling should also support overlapping annotations
- When clicking on an annotation: 
  - How to communicate which annotation is selected?
  - Should we show additional info about annotation? 
  - How to navigate to annotation pane/new search page/external entity browser?

**Comment by BasLee** [comment]
PR: https://github.com/knaw-huc/textannoviz/pull/132

**Comment by svandaalen** [comment]
This has been implemented for Republic.
