### ISSUE TITLE
Clean up state stores

### ISSUE THREAD

**Issue by BasLee** [knaw-huc/textannoviz#12]
The zustand stores have been growing dynamically, just like textannoviz itself, for the last few months. Some state has been incorporated in the stores, and other state is passed around through props. The stores need to be cleaned up. Some state can be moved to local props, and other state should be incorporated in the stores.

First, we should create some guidelines for what state should be managed locally by components, and what state should be managed by the store. 

With these guidelines, we can walk through the code and refactor the components and store slices accordingly.

**Comment by svandaalen** [comment]
The state stores have already been cleaned up.
