### ISSUE TITLE
Remove `_.uniqBy` when annotation duplication has been fixed in anno repo and tested in tav

### ISSUE THREAD

**Issue by BasLee** [knaw-huc/textannoviz#135]
[Duplication] should not be possible. If there are annotations with the same `body.id`, it's an error in the data. If you have any examples, or it happens again, you should let Bram know.

_Originally posted by @svandaalen in https://github.com/knaw-huc/textannoviz/pull/132#discussion_r1682444856_

**Comment by svandaalen** [comment]
Bram removed the duplicate `body.id`s in Republic's AR container 2024.07.18. Testing has found that the `.uniqBy()` is no longer necessary and has been deleted.
