### ISSUE TITLE
Conditionally import annotation css

### ISSUE THREAD

**Issue by BasLee** [knaw-huc/textannoviz#137]
When building project with showAnnotations=false tailwind still imports annotations.css during a build, resulting in this exception:
```
[vite:css] [postcss] */textannoviz/src/components/Text/Annotated/annotated.css?used:69:5: The `bg-annotation-per500/10` class does not exist. If `bg-annotation-per500/10` is a custom class, make sure it is defined within a `@layer` directive.
file: */textannoviz/src/components/Text/Annotated/annotated.css?used:69:5
error during build:
```

**Comment by svandaalen** [comment]
This has been fixed by adding a default Tailwind config file, which includes the entity annotation styling. The project-specific Tailwind configs now extend the default config.
