### ISSUE TITLE
Local docker environment depends on deleted files

### ISSUE THREAD

**Issue by boisei0** [knaw-huc/textannoviz#141]
In order to use the local docker environment (https://github.com/knaw-huc/textannoviz/blob/54a3d1c08a7e96f4dd7808328e26465e19908706/docker-compose-local.yml) that is included with Textannoviz, a defined nginx configuration file is needed. This file was removed in commit 945698b, having been marked as unused. The second file that got deleted in the same commit is also accessed in the local docker compose file. Was this environment supposed to have been deleted with the other files, as several changes appear to be needed to get it back to running.

**Comment by svandaalen** [comment]
This local docker file/environment is indeed no longer used. To run Textannoviz locally, you can follow the instructions in the README. I will delete the local docker file at a later moment. Thanks for pointing this out!
