### ISSUE TITLE
Fetch `tei:Note` annotations with separate 🥦 call

### ISSUE THREAD

**Issue by svandaalen** [knaw-huc/textannoviz#150]
For the visualisation of the footnotes in the text component, TAV needs access to the `tei:Note` annotations. The tier 1 annotation has recently been changed from `tf:File` to `LetterBody` for indexing purposes. The `LetterBody` annotation now includes only the main text body of the letter, while the `tf:File` annotation also includes the footnotes (and possibly other appendices or secretarials). Suriano did not want that text to be searchable; thus, the `LetterBody` was created. The tier 1 annotation that gets indexed is also the annotation that TAV shows in the detail view. Because the `LetterBody` annotations no longer include the footnotes, the `tei:Note` annotations also no longer overlap with the `LetterBody` annotations, resulting in the `tei:Note` annotations no longer appearing in the Broccoli results.

To get the `tei:Note` annotations that belong to the letter, you must do an extra Broccoli call using the `tf:File` annotation. The `tf:File` annotation still overlaps with the `LetterBody` annotation, meaning TAV can access this `tf:File` annotation after the initial call. Something similar – doing an extra call to gather additional info – is already done for Republic to get the attendants present during a Resolution. You can see that code here:

https://github.com/knaw-huc/textannoviz/blob/e3c7892b78106d1389041b00a9cce9c44912f614/src/projects/republic/MetadataPanel.tsx#L61-L90

You will need to change this code in multiple places:
- Find `tf:File` annotation instead of session annotation
- Use the id of the `tf:File` annotation
- Ask for `tei:Note` annotation instead of the `AttendanceList` annotation
- Ask for both `anno` and `text`
- Change `"self"` to all possible text panels
- Set `relativeTo` from `"Scan"` to `"Origin"`?

You will get something like this:
```ts
const annotations = useAnnotationStore().annotations;
const fileAnno = annotations.find(
    (anno) => anno.body.type === "tf:File",
  );
async function fetchData() {
  if (!fileAnno) return;
  const result: Broccoli = await fetchBroccoliScanWithOverlap(
    fileAnno.body.id,
    ["tei:Note"],
    ["anno", "text"],
    projectConfig.allPossibleTextPanels.join(","),
    "Origin",
    projectConfig,
    signal,
  );
//Do something with "result"
}
```

You might need to experiment with a few of the parameters to get it working correctly.

**Comment by BasLee** [comment]
See [90ba95d](https://github.com/knaw-huc/textannoviz/pull/154/commits/90ba95d30fac11bed7d161f93ccf5c94435e46eb)
