### ISSUE TITLE
Visualise the province of origin of the identified delegates in the metadata panel between brackets (REPUBLIC)

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#167]

**Comment by svandaalen** [comment]
@joddens, het lijkt erop dat TAV (nog) geen toegang heeft tot deze data.

@brambg, in de `Attendant` annotatie, of in `body.attendanceSpans` van de `AttendanceList` annotatie, zie ik niets over de provincie waar de aanwezige vandaan kwam. Is deze informatie wel beschikbaar in de CAF data?

**Comment by brambg** [comment]
@svandaalen Ik kan in de caf indexen die ik voor het maken van de republic web annotations gebruik niets voor de hand liggends vinden over provincies, in ieder geval niet op een gestructureerde manier.
Check het nog even met Marijn, zou ik zeggen.

**Comment by svandaalen** [comment]
Ik heb Marijn een pb gestuurd op Slack.

**Comment by marijnkoolen** [comment]
Dit zit niet in de CAF data, maar kan volgens mij uit RAA gehaald worden. Dat zal dus niet volledig zijn, maar waar we de info (denken te) hebben is het een nuttige toevoeging. 

@hoekr kun jij hier meer over zeggen?
