### ISSUE TITLE
Make references to dates (datums) that fall within references to resolutions in the text panel clickable (REPUBLIC)

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#170]
Clicking on these dates should direct the user to the search screen, where all resolutions of that particular date are shown (so the results of a search query in which the date facet is set to that date).

This should only be applied to those dates in the dataset 'dates' that overlap with resolutions in the dataset 'resolutions'.

**Comment by svandaalen** [comment]
Bram heeft op 10 september een nieuwe AR container online gezet met daarin `DateOccurrence` annotaties: https://annorepo.republic-caf.diginfra.org/w3c/republic-2024.09.10/1c03b754-fffe-464a-a169-1be6d88f02d8. Deze kunnen gebruikt worden voor het visualiseren in de tekst. `body.metadata.date` kan gebruikt worden in de zoekquery voor zowel `from` als `to`.

**Comment by svandaalen** [comment]
This has been implemented in #177.
