### ISSUE TITLE
Visualiseer in het metadatapaneel welk van de aanwezigen tijdens de desbetreffende zittingsdag voorzitter is (Republic).

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#171]
Dit moet ook in de CAF-data worden opgenomen, dat is nu nog niet het geval.

Rik en ik stellen voor om dit te visualiseren door middel van een voorzittershamericoontje achter de naam van deze persoon. We zullen @Doppen vragen of hij zo'n icoontje kan maken.

**Comment by svandaalen** [comment]
Bas heeft vandaag het icoontje aan TAV toegevoegd: https://github.com/knaw-huc/textannoviz/commit/ffcd3d57ac5c75d14a78ac9d92e16c3c1a263517. Ik zal deze op een later moment implementeren in het metadatapaneel.

**Comment by svandaalen** [comment]
@joddens, kun jij een schatting geven van wanneer jullie het in de CAF-data verwachten? En moet dit nog voor 9 oktober geïmplementeerd worden?
