### ISSUE TITLE
default datums in datumfacet aanpassen (REPUBLIC)

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#183]
In de datumfacet moeten de default-datums worden aangepast naar de begin- en einddatums van de vergadering (10/01/1576 en 03/01/1796)

**Comment by svandaalen** [comment]
Staat live op https://test-textannoviz.republic-caf.diginfra.org/ en is ook in de code aangepast :).

**Comment by joddens** [comment]
Ik weet trouwens niet zeker wat de startdatum was (augustus of oktober), omdat ik niet beschik over de vroegste resoluties. Voor nu maakt het nog niet uit want de eerste paar jaar zitten er nog niet in.
