### ISSUE TITLE
When adding facet `attendantId`, broccoli returns a `400`: "Missing 'fixed:' section in logical field: attendantId"

### ISSUE THREAD

**Issue by BasLee** [knaw-huc/textannoviz#209]
`curl -s 'https://broccoli.tt.di.huc.knaw.nl/projects/republic/search?indexName=republic-2024.09.19&fragmentSize=100&from=0&size=10&sortBy=_score&sortOrder=desc' -X POST -H 'Content-Type: application/json' --data-raw '{"terms":{"textType":["handwritten"],"organisationId":["O0000167"],"attendantId":["urn:republic:delegate:4"]},"date":{"name":"sessionDate","from":"1576-01-10","to":"1796-01-03"},"range":{"name":"text.tokenCount","from":"0","to":"66000"},"aggs":{"attendantId":{"order":"countDesc","size":10},"attendantName":{"order":"countDesc","size":10},"commissionId":{"order":"countDesc","size":10},"commissionName":{"order":"countDesc","size":10},"commissionLabels":{"order":"countDesc","size":10},"locationId":{"order":"countDesc","size":10},"locationName":{"order":"countDesc","size":10},"locationLabels":{"order":"countDesc","size":10},"organisationId":{"order":"countDesc","size":10},"organisationName":{"order":"countDesc","size":10},"organisationLabels":{"order":"countDesc","size":10},"personId":{"order":"countDesc","size":10},"personName":{"order":"countDesc","size":10},"personLabels":{"order":"countDesc","size":10},"roleId":{"order":"countDesc","size":10},"roleName":{"order":"countDesc","size":10},"roleLabels":{"order":"countDesc","size":10},"bodyType":{"order":"countDesc","size":10},"propositionType":{"order":"countDesc","size":10},"resolutionType":{"order":"countDesc","size":10},"textType":{"order":"countDesc","size":10},"sessionDate":{"order":"countDesc","size":10},"sessionDay":{"order":"countDesc","size":10},"sessionMonth":{"order":"countDesc","size":10},"sessionYear":{"order":"countDesc","size":250},"sessionWeekday":{"order":"countDesc","size":10}}}' | jq`

**Comment by hayco** [comment]
Hier gaat 🥦 dus nog niet goed om met een facet dat geen 'fixed value' nodig heeft.
Even op studeren...
