### ISSUE TITLE
'Terug naar zoekresultaten' button no longer shows previous search results

### ISSUE THREAD

**Issue by svandaalen** [knaw-huc/textannoviz#236]
TAV no longer performs a search query when the user clicks the 'terug naar zoekresultaten' button. The previous search query gets filled into the interface, but no query is executed.

<img width="1495" alt="image" src="https://github.com/user-attachments/assets/76a55990-8498-4576-bc87-3259174f4239">

**Comment by svandaalen** [comment]
TAV no longer searches because the decoded query is the same as the default query? I have to dive into this next week.

**Comment by BasLee** [comment]
Fixed in https://github.com/knaw-huc/textannoviz/pull/252
