### ISSUE TITLE
Categorieën in metadatapaneel van elkaar scheiden met puntkomma's (Republic)

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#244]
Wanneer achter 'Categorie' meerdere categorieën worden genoemd, moeten die van elkaar worden gescheiden met een puntkomma in plaats van een komma.

Anders ontstaat verwarring met Categorieën van het soort 'Handel, nijverheid & kunst', die ook een komma hebben

**Comment by BasLee** [comment]
See https://github.com/knaw-huc/textannoviz/pull/255
