### ISSUE TITLE
Entiteitenfacetten default op A-Z sortering zetten (Republic)

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#245]

**Comment by BasLee** [comment]
@svandaalen Willen we de configuratie van `defaultKeywordAggsToRender` aanpassen, dat je behalve de naam ook een optionele sort order kunt meegeven?

**Comment by svandaalen** [comment]
Ik denk dat overrides toegevoegd kunnen worden aan `overrideDefaultAggs` (L67) in de config. Hier zijn `facetName`, `order` en `size` nog verplicht, maar misschien dat we `order` en `size` optioneel kunnen maken. Voor implementatie hiervan, zei `createAggs.ts`.
