### ISSUE TITLE
Aanpassen volgorde facetten in facettenpaneel (Republic)

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#248]
De volgorde van de facetten moet worden aangepast:Teksttype, Resolutietype, Propositietype, Aanwezige gedeputeerden (entiteit), Persoonsnaam (entiteit), Persoonsnaam (categorie) Hoedanigheid (entiteit), Hoedanigheid (categorie), Locatie (entiteit), Locatie (categorie), Organisatie (entiteit), Organisatie (categorie), Commissie (entiteit), Commissie (categorie), Weekdag, Aanwezige gedeputeerden (ID), Persoonsnaam (ID), Hoedanigheid (ID), Locatie (ID), Organisatie (ID), Commissie (ID), Type

**Comment by svandaalen** [comment]
- Teksttype
- Resolutietype
- Propositietype
- Aanwezige gedeputeerden (entiteit)
- Persoonsnaam (entiteit)
- Persoonsnaam (categorie)
- Hoedanigheid (entiteit)
- Hoedanigheid (categorie)
- Locatie (entiteit)
- Locatie (categorie)
- Organisatie (entiteit)
- Organisatie (categorie)
- Commissie (entiteit)
- Commissie (categorie)
- Weekdag
- Aanwezige gedeputeerden (ID)
- Persoonsnaam (ID)
- Hoedanigheid (ID)
- Locatie (ID)
- Organisatie (ID)
- Commissie (ID)
- Type

**Comment by hayco** [comment]
Verwerkt in de 🥦 configuratie op api.goetgevonden.nl
