### ISSUE TITLE
Placeholder openingsscherm vervangen door tekst (Republic)

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#250]

**Comment by svandaalen** [comment]
@joddens, kun je ons laten weten wanneer jullie deze tekst gereed hebben?

**Comment by joddens** [comment]
hier is de definitieve versie
[tekst placeholder_jip_en_janneke.docx](https://github.com/user-attachments/files/17832671/tekst.placeholder_jip_en_janneke.docx)
