### ISSUE TITLE
Links naar entiteitenmodal toevoegen aan gedeputeerden in metadatapaneel (republic)

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#257]

**Comment by svandaalen** [comment]
We vinden het lastig te zien welke extra's zo'n entiteitenmodal toevoegt. Je ziet dan nogmaals de naam van de gedeputeerde en kunt dan een nieuwe zoekquery doen naar alle resoluties waarbij die gedeputeerde aanwezig was en je kunt via de modal naar de entiteitenbrowser gaan. Dit is nodeloos complex. We stellen voor om het volgende te doen:

- de naam van de gedeputeerde wordt een link naar de entiteitenbrowser (zoals je in het verleden naar de RAA ging)
- we voegen achter de naam van de gedeputeerde een loep-icoon toe waarmee je de zoekquery kunt uitvoeren

**Comment by svandaalen** [comment]
Zie ook #172.

**Comment by joddens** [comment]
De door jullie voorgestelde oplossing lijkt me uitstekend.
