### ISSUE TITLE
Naam van de facet 'Filter Facet' aanpassen (Republic)

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#264]
Naam aanpassen van 'Filter facet' naar 'Filter instellen'

Motivatie: uit de testsessie bleek dat veel gebruikers niet bekend zijn met de term 'Facet'. 

In de documentatie worden ook consequent gesproken van 'filters' en niet van 'facetten'

De huidige naam nodigde er niet toe uit te bekijken welke facetten er nog meer waren.

**Comment by BasLee** [comment]
Fixed in https://github.com/knaw-huc/textannoviz/pull/280
