### ISSUE TITLE
Infotekstje bij 'Vrij zoeken' aanpassen (Republic)

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#265]
Achter de info-knop van het vrije zoekveld staat „Plaats ‘~1’ of een groter getal achter de term als het resultaat 1 of meer karakters mag afwijken.” – Maar alleen ~1 en ~2 zijn daadwerkelijk toegestaan: ~3 geeft een foutmelding. Een betere tekst is dus: Plaats ‘~1’ of ‘~2’ achter de term als het resultaat 1 of 2 tekens mag afwijken.”

**Comment by BasLee** [comment]
Fixed in https://github.com/knaw-huc/textannoviz/pull/283/files
