### ISSUE TITLE
Hanteer voor het entiteitstype 'Persoonsnaam' consequent de naam 'Persoonsnaam' (Republic)

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#267]
Het entiteitstype 'Persoonsnaam' heette voorheen 'Persoon'. Dit is nu aangepast in de facetten 'Persoonsnaam (entiteit)', 'Persoonsnaam (categorie)' en 'Persoonsnaam (ID)', maar nog niet in de entiteitenmodal en het metadatapaneel.

**Comment by BasLee** [comment]
Fixed in https://github.com/knaw-huc/textannoviz/pull/281
