### ISSUE TITLE
Filter and/or search by VOC inventory number

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/textannoviz#60]
Make it easier/explicit how to facet (or perhaps also search) for an inventory number (e.g. NL-HaNA_1.04.02_7976_0105). However, these are two different things. Filtering will just limit/restrict what is displayed. But what should be shown if you explicitly search for an inventory number? What counts as results? For example, one could list all the pages of that inventory in the search results. In this way, one could browse through the listing and then switch to detail view to see the transcription. In addition, the snippet context doesn’t straightforwardly apply here and would likely need to be disabled (for this type of search).

Very probably, this issue will need to be split into two (one to facet on inv. numbers, one to search on them).

**Comment by kintopp** [comment]
There have been multiple user requests for this (though users didn't attempt to make / didn't think through the facet/search distinction).

**Comment by kintopp** [comment]
https://globalise.canny.io/transcriptions-viewer/p/add-a-way-to-filter-search-results-by-voc-inventory-number

**Comment by svandaalen** [comment]
First version has been implemented. Waiting on feedback from the Globalise team.
