### ISSUE TITLE
Mirador navigation elements appear in wrong location

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/textannoviz#66]
If you carry out a search, then click on one of the results, the navigation elements in the image viewer appear correctly. However, if you carry out a search, then change the number of results per page setting, and only then click on a result, the viewer’s navigation elements appear in the wrong place. This can sometimes (?) also be triggered by carrying out a few searches, and then clicking to the detail view, or by first navigating to other pages of the search results. Refreshing the page fixes their position.

**Comment by svandaalen** [comment]
For Republic I have built a version of Mirador using their latest commit which upgrades MUI4 to MUI5. Since then I have not heard no complains about this bug anymore. Globalise will get this version of Mirador in the next release of TAV. Could you monitor for this bug after the next release?

**Comment by svandaalen** [comment]
Haven't heard about this problem since implementing the new Mirador version, so I am closing this issue. If it pop ups again, a new issue will be created.
