### ISSUE TITLE
Fix *commi* NOT gecommitteerden in Help examples or possible bug

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/textannoviz#68]
This example from the Help doesn’t appear to be a valid expansion: `*commi* NOT gecommitteerden` The problem is with the double asterix on `*commi*` In that case the example [on the help page](https://transcriptions.globalise.huygens.knaw.nl/help) needs to be changed. Or, it could be a bug.

**Comment by svandaalen** [comment]
The Republic search help writes:
> Voorbeeld: ‘(commis* OR gecommit*) NOT **gecommitteerden**’ -> U krijgt resultaten waarin woorden voorkomen die beginnen met ‘commis’ of ‘gecommit’, maar waar het woord ‘gecommitteerden’ niet in voorkomt. N.B.: deze zoekopdracht is te vereenvoudigen tot ‘*commi* NOT gecommitteerden’).

The Globalise search help writes:
> For example: (commis* OR gecommit*) NOT **committeeren** will find results containing words starting with commis or gecommit, but not containing the word committeeren. Note: this search can also be simplified to *commi* NOT gecommitteerden.

The word in bold is different between the two help pages. Correct in the Globalise search help should be "*commi* NOT committeeren" (without quotes). I think the query does what it needs to.
