### ISSUE TITLE
Revise wording for search results counter to distinguish pages from instances

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/textannoviz#72]
Revise the wording for the search results counter. For example, 1-10 of 878 results really means 1-10 of 878 pages containing the search term. The actual number of instances of the keyword will be much higher if it appears more than once on a page. Change to ‘1-10 of 878 pages’.

**Comment by svandaalen** [comment]
[This commit](https://github.com/knaw-huc/textannoviz/commit/8233964bb03157e75e3dee1675324914ce62ae22) made the search results string configurable per project. I have set it to "pages" for Globalise, meaning you will get "1-10 of 878 pages".

**Comment by kintopp** [comment]
This is currently implemented on the development instance, right?

**Comment by svandaalen** [comment]
That is correct. Once a new version is deployed, the change will be visible in the Globalise Transcription Viewer.

On 8 Aug 2024, at 13:50, Arno Bosse ***@***.***> wrote:



This is currently implemented on the development instance, right?
