### ISSUE TITLE
Make layout of help page consistent with search page 

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/textannoviz#75]
Split and style the content area under the title on the [Help page](https://transcriptions.globalise.huygens.knaw.nl/help) to match the [search/landing page](https://transcriptions.globalise.huygens.knaw.nl/). Use the area to the left of main content area for anchor links to different sections of the Help text.

**Comment by svandaalen** [comment]
Implemented in https://github.com/knaw-huc/textannoviz/commit/f59a48cbedb9866eacabf91664fba077a3fcc262.

Waiting on updated Help text.

**Comment by kintopp** [comment]
Waiting on decision on how #108 will be implemented so I can finish the help page ;^) But in the meantime, please already take a look at https://github.com/globalise-huygens/transcriptions-viewer-documentation/blob/main/tav-search-help-v03.html and https://github.com/globalise-huygens/transcriptions-viewer-documentation/blob/main/tav-help-anchor-links-v03.html Would this work for you?

**Comment by svandaalen** [comment]
Yes, I am in the process of integrating those at this moment :)!

**Comment by svandaalen** [comment]
Implemented updated Help text and links. Waiting on feedback from the Globalise team.
