### ISSUE TITLE
Search for an inventory number as keyword leads to incorrect highlights in detail view

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/textannoviz#78]
If you search for an inventory number as keyword, e.g. NL-HaNA_1.04.02_4026_0350 and select it in detail view each space between letters in the transcript is highlighted. If you paste the URL of the detail view into a new browser window, the transcript appears without highlights. 

We're not telling our users to search search for an inventory number as keyword (so in that sense it's not a bug) but I suspect that it might be bug anyway :)

**Comment by svandaalen** [comment]
I can't reproduce this bug anymore, so I think this has already been fixed.
