### ISSUE TITLE
Connect histogram date filer and search date filter

### ISSUE THREAD

**Issue by marijnkoolen** [knaw-huc/textannoviz#81]
Currently, there is a date filter in the search bar and a separate one in the histogram panel. Updating one does not update the other. I have three requests:

1. connect the two filters so that updating one, updates the other (or remove one and trigger search update and histogram update via the same date filter)
2. add a reset button to the date filter in the histogram (unless the two filters are collapsed into one).
3. restrict the range of the histogram filter to the range of the data (either hard-coded or based on min and max date in the ES index. (again, unless the two filters are collapsed into one).

**Comment by svandaalen** [comment]
For now I have decided to collapse the two filters into one. This means that the histogram is now controlled by the date facet. The next step is to improve the functionality of the date facet. See also #82.

The downside of this decision might be that the user can't create custom views on the data in the histogram. If this request comes in sometime, I can look into adding a separate filter for the histogram again.

Related commit: https://github.com/knaw-huc/textannoviz/commit/42d91a8d7b8522369c115dc956a446ffc82aab28.
