### ISSUE TITLE
Error messages while manually inserting date in date facet

### ISSUE THREAD

**Issue by joddens** [knaw-huc/textannoviz#82]
Als je een datum aan het invullen bent in het datumfacet krijg je een hele reeks errorpop-ups

**Comment by svandaalen** [comment]
The error pop-ups have been disabled for now. The next step is to improve the date facet.

**Comment by svandaalen** [comment]
In commit https://github.com/knaw-huc/textannoviz/commit/60d1012bc0f537a14eb00fb5df777f1e48682364 I have improved the UX of the date facet. It should now handle invalid dates better. The manually entering of the date should also work smoother.
