### ISSUE TITLE
Add footnote marker in text

### ISSUE THREAD

**Issue by svandaalen** [knaw-huc/textannoviz#89]
For Suriano, there should be a footnote marker in the text (like in Word) and when the user hovers over the footnote marker, a popup should appear with the contents of that footnote.

It appears that the `tei:Ptr` annotations points to the place in the text where that marker should be added. The `tei:Note` annotation is the contents of the note and the `start` and `end` mark the location of the note in the textstream of the letter.

**Comment by brambg** [comment]
The tei:Ptr body looks like:
"body": {
      "id": "urn:suriano:ptr:337607",
      "type": "tei:Ptr",
      "tf:textfabricNode": 337607,
      "metadata": {
        "n": "1",
        "target": "#tn1",
        "type": "tt:PtrMetadata"
      }
    },

where body.metadata.target (without the # prefix) indicates which note is pointed to.

The tei:Note body looks like:
"body": {
      "id": "urn:suriano:note:327351",
      "type": "tei:Note",
      "tf:textfabricNode": 327351,
      "metadata": {
        "tei:id": "tn1",
        "lang": "en",
        "type": "tt:NoteMetadata"
      }
    }
where the body.metadata.tei:id is part of the relevant data for connecting Ptr to Note
In the query to annorepo you'd need to look for tei:Note annotations with the given body.metadata.tei:id and a target.source that is the same as the target.source from the tei:Ptr annotation

**Comment by brambg** [comment]
Also, the notes have rendering information that might have to be used:
https://gitlab.huc.knaw.nl/suriano/letters/-/blob/main/tei/2023-07-25/4/0001.xml?ref_type=heads#L237

**Comment by BasLee** [comment]
At the moment the relative view annotations are only present in the self view. Waiting for changes in broccoli.

**Comment by svandaalen** [comment]
Done.
