### ISSUE TITLE
Browse through Suriano corpus in chronological order

### ISSUE THREAD

**Issue by svandaalen** [knaw-huc/textannoviz#91]
This means that the order should be included in the data? Can I use the `body.metadata.file` of the `tf:File` annotation? But I don't know where the integer range ends. 

Example `body.metadata` of a `tf:File`:
```JSON
"body": {
    "id": "urn:suriano:file:302739",
    "type": "tf:File",
    "tf:textfabricNode": 302739,
    "metadata": {
      "date": "1617-01-28",
      "editornotes": "",
      "file": "0041",
      "recipient": "Venice, Doge, Senate and citizens of",
      "recipientloc": "Venice",
      "sender": "Suriano, Cristoforo",
      "senderloc": "L’Aia",
      "shelfmark": "Senato, Dispacci, Signori Stati, Filza 3, fol 270-273v",
      "summary": "Some Frenchmen have arrived from Paris coming from Savoyard camp claiming the Duke of Savoy pays badly. The Dutch ambassador Langerack writes about Digheris, further problems between France and England about the execution on treaty of Xanten. He ends the letter by include the note that two whales have been stranded in Den Briel, he adds that he hopes this will the change the direction of wind.",
      "type": "tt:FileMetadata",
      "manifest": "https://images.diginfra.net/api/pim/imageset/67533019-4ca0-4b08-b87e-fd5590e7a077/manifest"
    }
  },
```

**Comment by brambg** [comment]
the `body.metadata.file` are re-used in filzas 3 and 4, so this would not be a simple way to find next/prev.
Extra metadata fields `prevFile` / `nextFile` need to be added in either the TF or the AR phase.

**Comment by brambg** [comment]
@dirkroorda , is het mogelijk om bij de `tf:File` annotaties velden `prevFileNode` en `nextFileNode` op te nemen. waarbij de value van de velden de `tf:textfabricNode` van voorgaande en volgende `tf:File` annotatie is?

**Comment by dirkroorda** [comment]
@brambg 
Zeker. Wat ik nu deed was die TF node te pakken nemen, de relevante features ervan opvragen, en die in het url template invullen.

Wat je nu vraagt is makkelijker.

**Comment by brambg** [comment]
Mooi, doe het voor de next/prev bij de `tf:Page` annotaties ook maar, dan. I.p.v. de urls die je er nu inzet. Met dat node nummer kan ik dan naar de juiste `Page` annotation `body` verwijzen, en het node nummer is altijd uniek, in tegenstelling tot de page urls, o.a. bij je `466vC` voorbeeld.

**Comment by dirkroorda** [comment]
De vorige en volgende nodes van hetzelfde type in TF zijn altijd de node min 1 resp. plus 1, tenzij je de eerste of laatste node van dat type te pakken hebt.
Hoewel, het is denk ik toch een implementatiedetail van de nodes in TF, ik moet eens kijken of het gegarandeerd is. Ik zal in ieder geval die annotaties er in zetten zoals jij dat wilt.

Wat wil je bij de prev van de eerste node hebben, en bij de next van de laatste node?

**Comment by brambg** [comment]
De prev van de eerste en de next van de laatste mogen ontbreken.

**Comment by dirkroorda** [comment]
Ok, op dit moment wijze beide naar "zichzelf".
